### ISSUE TITLE
Structure of this repo

### ISSUE THREAD

**Issue by matthew16550** [plantuml/plantuml-test#1]
Here is what I am thinking for this repo.

It should use tooling & versions very similar to https://github.com/plantuml/plantuml but doesn't need to be exactly the same, so:

* Java 1.8.
* Maven 3.6.3 (the latest) with [maven-wrapper](https://github.com/takari/maven-wrapper).
* Maven TEST dependencies on `net.sourceforge.plantuml/plantuml` & `org.scilab.forge/jlatexmath`.
* No other external dependencies for now (pending your bigger picture discussion on how PlantUML will do testing).
* GitHub action to build & to run a simple smoke test.
* No artefacts published & no versioning for now.

@arnaudroques your thoughts?

**Comment by arnaudroques** [comment]
That's fine.
You can also use JUnit or TestNG for testing if you want/need.
Thanks!

**Comment by matthew16550** [comment]
Also I suggest a [.editorconfig](http://editorconfig.org) file, been using them everywhere I can in the last few years as they help to spread harmony and cooperation!

PlantUML uses a mixture of tabs & spaces, is there a preference?

**Comment by matthew16550** [comment]
@arnaudroques your thoughts on tabs / spaces ⬆️  ?
I'd like to decide that before committing the test code.

**Comment by arnaudroques** [comment]
Let's go for TAB !

**Comment by matthew16550** [comment]
I'll close this for now, could re-open later if there's more to discuss.
